### ISSUE TITLE
stopping in the middle

### ISSUE THREAD

**Issue by nviennot** [flott-motion/ramp-maker#44]
What if we want to immediately stop while on motion, and respect the acceleration constraint?

Calling `enter_position_mode(0,0)` won't work. It will stop the motor abruptly.

**Comment by hannobraun** [comment]
Hmm, I did a quick review of the code ([`RampMode::compute`](https://github.com/braun-embedded/ramp-maker/blob/f923f36b1a6b519bf5f54f785bf434b6d3576ba5/src/trapezoidal.rs#L208-L257) and [`Trapezoidal::next_delay`](https://github.com/braun-embedded/ramp-maker/blob/f923f36b1a6b519bf5f54f785bf434b6d3576ba5/src/trapezoidal.rs#L151-L184) are the relevant parts, I believe). I *think* this should work. If `Trapezoidal` believes the motor is still moving, that should result in it [going into `RampDown` mode](https://github.com/braun-embedded/ramp-maker/blob/f923f36b1a6b519bf5f54f785bf434b6d3576ba5/src/trapezoidal.rs#L241) which should then result in a [controlled deceleration](https://github.com/braun-embedded/ramp-maker/blob/f923f36b1a6b519bf5f54f785bf434b6d3576ba5/src/trapezoidal.rs#L174).

But that's just from a quick review of the code, so I might be wrong. And there is no unit test for this specific scenario that could back me up here.

How are you using RampMaker? What exactly is stopping the motor abruptly (since RampMaker itself doesn't control motors; it just generates the delays between pulses)? What is `Trapezoidal::next_delay` returning when the motor abruptly stops?

Besides digging into the problem by answering these questions, it would be a good idea to add a unit test to [`Trapezoidal`'s test suite](https://github.com/braun-embedded/ramp-maker/blob/f923f36b1a6b519bf5f54f785bf434b6d3576ba5/src/trapezoidal.rs#L260-L455), to make sure it actually behaves correctly in this situation.

**Comment by hannobraun** [comment]
Closing due to lack of feedback.
